export const AUTH = "/";
export const PAY = "/payment";
export const HOME = "/home";
export const CARD = "/card";
export const CREDIT = "/credit";
export const BILL ="/bill";
export const USER = "/user";
export const CURRENCY = "/currency"
export const ATMS = "/atm"
export const HISTORY = "/history"